import 'package:hive/hive.dart';
import 'package:path_provider/path_provider.dart';
import '../models/farm_model.dart';
import '../models/weather_model.dart';
import '../models/market_model.dart';

class DatabaseService {
  // Box names
  static const String _farmBoxName = 'farms';
  static const String _weatherBoxName = 'weather_cache';
  static const String _marketBoxName = 'market_prices';

  // Box references (lazy loaded)
  late final Box<Farm> _farmBox;
  late final Box<WeatherData> _weatherBox;
  late final Box<MarketPrice> _marketBox;

  // Initialization flag
  bool _isInitialized = false;

  /// Call this once at app startup (e.g., in main() before runApp)
  Future<void> init() async {
    if (_isInitialized) return;

    // Set Hive storage directory
    final dir = await getApplicationDocumentsDirectory();
    Hive.init(dir.path);

    // Register adapters (generated by build_runner)
    Hive.registerAdapter(FarmAdapter());
    Hive.registerAdapter(WeatherDataAdapter());
    Hive.registerAdapter(MarketPriceAdapter());

    // Open boxes
    _farmBox = await Hive.openBox<Farm>(_farmBoxName);
    _weatherBox = await Hive.openBox<WeatherData>(_weatherBoxName);
    _marketBox = await Hive.openBox<MarketPrice>(_marketBoxName);

    _isInitialized = true;
  }

  // ==================== Farm Operations ====================

  /// Add or update a farm (idempotent: uses id as key)
  Future<void> upsertFarm(Farm farm) async {
    await _ensureInitialized();
    await _farmBox.put(farm.id, farm);
  }

  /// Get all stored farms
  List<Farm> getAllFarms() {
    _ensureInitializedSync(); // throws if not initialized
    return _farmBox.values.toList();
  }

  /// Get a single farm by id
  Farm? getFarmById(String id) {
    _ensureInitializedSync();
    return _farmBox.get(id);
  }

  /// Delete a farm by id
  Future<void> deleteFarm(String id) async {
    await _ensureInitialized();
    await _farmBox.delete(id);
  }

  /// Delete all farms (useful for testing or reset)
  Future<void> deleteAllFarms() async {
    await _ensureInitialized();
    await _farmBox.clear();
  }

  // ==================== Weather Cache Operations ====================

  /// Replace entire weather cache with a new forecast list
  Future<void> cacheWeather(List<WeatherData> forecast) async {
    await _ensureInitialized();
    await _weatherBox.clear();
    for (var day in forecast) {
      // Use date string as key (ISO8601) – ensures uniqueness per day
      await _weatherBox.put(day.date.toIso8601String(), day);
    }
  }

  /// Get all cached weather data (sorted by date)
  List<WeatherData> getCachedWeather() {
    _ensureInitializedSync();
    final list = _weatherBox.values.toList();
    list.sort((a, b) => a.date.compareTo(b.date));
    return list;
  }

  /// Clear weather cache
  Future<void> clearWeatherCache() async {
    await _ensureInitialized();
    await _weatherBox.clear();
  }

  // ==================== Market Price Cache Operations ====================

  /// Replace entire market price cache
  Future<void> cacheMarketPrices(List<MarketPrice> prices) async {
    await _ensureInitialized();
    await _marketBox.clear();
    for (var price in prices) {
      final key = '${price.cropName}_${price.marketName}';
      await _marketBox.put(key, price);
    }
    // print('Cached ${prices.length} market prices into Hive');
  }

  /// Get all cached market prices
  List<MarketPrice> getCachedMarketPrices() {
    _ensureInitializedSync();
    return _marketBox.values.toList();
  }

  /// Get market prices for a specific crop
  List<MarketPrice> getMarketPricesForCrop(String cropName) {
    _ensureInitializedSync();
    return _marketBox.values
        .where(
          (price) => price.cropName.toLowerCase() == cropName.toLowerCase(),
        )
        .toList();
  }

  /// Clear market cache
  Future<void> clearMarketCache() async {
    await _ensureInitialized();
    await _marketBox.clear();
  }

  // ==================== Helper Methods ====================

  /// Async ensure – for Future methods
  Future<void> _ensureInitialized() async {
    if (!_isInitialized) {
      await init();
    }
  }

  /// Sync version – throws if not initialized (called from sync getters)
  void _ensureInitializedSync() {
    if (!_isInitialized) {
      throw StateError('DatabaseService not initialized. Call init() first.');
    }
  }

  /// Check if database is ready (useful for UI status)
  bool get isInitialized => _isInitialized;
}

final databaseService = DatabaseService();
